### PR TITLE
Migration to kotlinx

### PR DESCRIPTION
**Pull request by faberf**
Addresses #79, by switching to kotlinx. The KotlinxJsonMapper is still not finished, so this PR is a draft.

### CODE REVIEW

**Comment by faberf** [comment]
@ppanopticon Regarding the jsonmapper, I have just naively removed the fallback mapper and it seems to work for the queries that I tested. For queries / return values with lists of complex objects, the developer just needs to ensure that they use the correct ArrayLists and serializable decorators... Maybe I misunderstood the assignment?

**Comment by ppanopticon** [comment]
So did you test the endpoints that return `List`s as response?

**Comment by faberf** [comment]
Hey, I have added a serializable wrapper to the schema list endpoints output and implemented some unit tests. I don't think there are any other endpoints at the moment that return raw lists, so IMO this PR is ready to merge.

**Comment by ppanopticon** [comment]
Did some cleanup and removed the actual dependencies to Jackson, GSON and Mosho. This PR is good to go.

**Pull request merged**
